spring:
  datasource:
    url: ${SOULSNET_DATASOURCE_URL:jdbc:postgresql://localhost/pg_soulsnet}
    password: ${SOULSNET_DATASOURCE_USERNAME:postgres}
    username: ${SOULSNET_DATASOURCE_PASSWORD:postgres}
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  session:
    jdbc:
      initialize-schema=: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql

security:
  oauth2:
    client:
      clientId: 50683351725-uu326pr09j931upb03fvmlut7j5nlghj.apps.googleusercontent.com
      clientSecret: ${clientSecret}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid,email,profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true

sentry:
  dsn: ${sentryDSN}
  environment: production
  release: soulsnet@1.0.0
